### ISSUE TITLE
Sorry - But you probably won't answer your email

### ISSUE THREAD

**Issue by talonbragg** [KingPixil/moon#10]
For codecov, do I use my .travis.yml or codecov.yml or create a webhook in the repo? Sorry about this.

**Comment by KingPixil** [comment]
You can use any of those, I do it via Travis. Codecov generates the report by getting the coverage file (in this case, `coverage/coverage.json`), and parsing it to create graphs and updates the badge.

**Comment by talonbragg** [comment]
Ok thanks

**Comment by talonbragg** [comment]
Thanks, This actually really helped.

**Comment by talonbragg** [comment]
Hey @KingPixil how long does it take for the codecov to update?

**Comment by KingPixil** [comment]
What do you mean?

**Comment by talonbragg** [comment]
How long does it take for codecov to activate the repo on the site?

**Comment by KingPixil** [comment]
Usually around 30 seconds

**Comment by talonbragg** [comment]
Dang it is taking like 5 minutes

**Comment by talonbragg** [comment]
can you check the repo and see if there are any problems with the .travis.yml and that stuff

**Comment by KingPixil** [comment]
The build passed... do you have a codecov account?

**Comment by talonbragg** [comment]
well, I used github to sign in.

**Comment by KingPixil** [comment]
You don't have any tests either, and no tests means you aren't even instrumenting or generating a coverage report in the first place.

**Comment by talonbragg** [comment]
?

**Comment by talonbragg** [comment]
I used mocha, in the tests folder.

**Comment by KingPixil** [comment]
Well your build isn't even running them.

**Comment by talonbragg** [comment]
How do I get it to run them, does it have to do with the package.JSON?

**Comment by KingPixil** [comment]
And that test literally checks if `4` is not present in the array `[1, 2, 3]` (obviously true)

Shouldn't your tests test out your actual library? 
Running them is simple, setup travis to run the tests however you'd like (through gulp, node, etc)

**Comment by talonbragg** [comment]
well how would I do that, like with this? `scripts:`

**Comment by KingPixil** [comment]
If you'd like, then setup travis to run `npm run test` if you have a `test` script setup.

But your tests don't even test your library.

**Comment by talonbragg** [comment]
I Know they don't test my library, I just haven't added the code yet. My overall goal before I test the actual library itself is get the test on codecov to even work.

**Comment by KingPixil** [comment]
Well codecov won't even work if you don't test your library in the first place...

It's used to show how much of the library's code is used while running tests.

**Comment by talonbragg** [comment]
Oh, well any way here is the test code:

```javascript
var assert = require('assert');
describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
      assert.equal(-1, [1,2,3].indexOf(4));
    });
  });
});
```
Where would I put my library code in that.

**Comment by talonbragg** [comment]
I know I sound like a total idiot to you :slightly_frowning_face:

**Comment by KingPixil** [comment]
Well you can't just put your library code, you have to put a version of it analyzed by a code coverage tool to emit special events to store when a block of code is run into an object, and then writes this data to a `coverage.json` file. This is then referenced by codecov to generate a report that is understandable.

**Comment by talonbragg** [comment]
What code coverage tool? codecov

**Comment by KingPixil** [comment]
Blanket or Istanbul

**Comment by talonbragg** [comment]
Man I don't know if I should even use codecov

**Comment by talonbragg** [comment]
ok I'll try Blanket first

**Comment by KingPixil** [comment]
Codecov is just to display data from `coverage.json` in graphs.

**Comment by talonbragg** [comment]
ok

**Comment by talonbragg** [comment]
So I just need the blanket.js for it

**Comment by KingPixil** [comment]
For example here is how Moon's build works.

- Build files in `dist`
- Instrument code with Istanbul
- Run tests w/ Mocha + Chai (linking to the instrumented version of Moon)
  - Generate a `coverage.json` file with coverage data
- Run tests in different browsers via Saucelabs
- Send coverage data to codecov

**Comment by talonbragg** [comment]
k

**Comment by talonbragg** [comment]
GTG CYA

**Comment by KingPixil** [comment]
Bye

**Comment by talonbragg** [comment]
Kabir, I have the coverage.json and all of those files, got them from istanbul. They are on my computer, now do I just upload them to github so that codecov can do its thing?

**Comment by KingPixil** [comment]
You setup travis to generate the coverage report then send it to codecov

**Comment by talonbragg** [comment]
Nvm it doesn't matter. I got it this morning.

**Comment by talonbragg** [comment]
Dude can you do the test.js for me, I have no idea how to do it.

**Comment by KingPixil** [comment]
I don't think I will do it for you, because then how will you learn?

Here are some things that you should do:

- You have the whole library created again in the tests, just `require` it from the `dist` folder
  - If you want code coverage, setup a script to generate the coverage file, it will be the same as Mr Node, but will report coverage. `require` this file instead.
- You have no assertions, meaning Mocha can't pass, here is an example assert (with Chai)
```js
const path = require("path");

describe("mrnode#create", () => {
  it("should create a js file", () => {
    mrnode.create("somefile", "js");
    expect(path.join(__dirname, fs.existsSync("somefile.js"))).to.be.true;
  });
});
```

**Comment by talonbragg** [comment]
Is path a node module?

**Comment by KingPixil** [comment]
Yes

**Comment by talonbragg** [comment]
But I fill it in with my javascript file path?

**Comment by KingPixil** [comment]
Look at the docs...

**Comment by talonbragg** [comment]
Docs for what, chai?

**Comment by KingPixil** [comment]
Also, these issues are for Moon only, I think this should be enough help, if you need more, refer to the Mocha/Chai/Istanbul/Path/Gulp/Travis/Codecov docs
