### ISSUE TITLE
msg and input example

### ISSUE THREAD

**Issue by talonbragg** [KingPixil/moon#12]
The example on the website has one little bug that you might want to fix. When there is no text in the msg area, the input box moves upward. This is kind of annoying. Could you please fix this, thanks.

**Comment by KingPixil** [comment]
Which example? There are many examples in the docs. Can you provide a picture/gif of what is happening?

**Comment by KingPixil** [comment]
Never mind, I see what you mean, this is simply Moon's diffing engine generating no element due to no text being present (a feature, not a bug).

If you open developer tools, you'll see the `<h1>` element being removed completely.

**Comment by talonbragg** [comment]
The one on the main page man.

**Comment by KingPixil** [comment]
Yeah, I saw. The `<h1>` element has no content when there is no content, meaning it has dimensions of 0x0, leading to the input jumping up.
