### ISSUE TITLE
Missing minified script

### ISSUE THREAD

**Issue by gokaygurcan** [KingPixil/moon#15]
Hello,

when I open http://moonjs.ga/, it tries to get minified version of the script but on gh-pages branch, there's no minified script in ./dist folder.

https://github.com/KingPixil/moon/blob/gh-pages/index.html#L100

As a result, it ends up with 404 and scripts.js also gets broken because of missing Moon dependency.

**Comment by KingPixil** [comment]
Thanks! Forgot to update it there

**Comment by gokaygurcan** [comment]
It works now, thanks again.
