### ISSUE TITLE
Object prop is passed to child component as string

### ISSUE THREAD

**Issue by pedroborges** [KingPixil/moon#18]
First of all, congrats for sticking to your idea and launching it! I'm a Vue.js fan and really like the idea of a lightweight alternative, specially for embedded apps.

I tried out Moon this afternoon and had a problem with props. I want to send data from the main Moon instance to a child component via props. Later this data will be loaded from an API.

```js
// app.js
const Moon = require('moonjs')
const ContactsIndex = require('./contacts/index.moon')(Moon)

new Moon({
    el: "#app",
    data: {
        contacts: [{name:"Pedro"},{name:"Augusto"},{name:"Borges"}]
    }
})
```

```js
// contacts/index.moon
<template>
    <h1>Contacts</h1>
    <ul>
        <li m-for="person in {{contacts}}">{{person}}</li>
    </ul>
</template>

<script>
    exports = {
        props: ['contacts']
    }
</script>
```

```html
<!-- /index.html -->
<div id="app" m-mask>
    <Index contacts="{{contacts}}"/>
</div>
```

Moon passes the object as a string and renders each character on a `li` element. Am I doing something wrong? I want to avoid converting and parsing JSON.

---

Another question… Is the component name tied to its file name? I want to organize components in folders and name them like so, `ContactsIndex`. Moon only accepts the `Index` name since the file is located at `contacts/index.moon`.

**Comment by KingPixil** [comment]
Thanks for using Moon, really appreciate you trying it out 😄 

By default (like in Vue), props are converted to strings during rendering to avoid performing a type conversion later on. Try using `m-literal:contacts="{{contacts}}"`

`m-literal` treats anything inside it as a literal Javascript expression, allowing for arrays, objects, strings, numbers, etc.

The component name is tied to the file name. Let me know how would you prefer setting the name of the component, and I can try implementing it 👍

**Comment by pedroborges** [comment]
Thanks for the quick reply! `m-literal` did the trick.

As for the name you could add a `name` option to the component as Vue.js does:

```js
exports = {
    name: 'contacts-index',
    props: ['contacts']
}
```

**Comment by KingPixil** [comment]
There is a name option right now, but it won't work (it is overridden). It will be added in v0.8.0 along with computed properties (with cache), much better performance, and a couple more bug fixes ⚡️
