### ISSUE TITLE
Lexical analyzer has some problems

### ISSUE THREAD

**Issue by wangning0** [KingPixil/moon#19]
if your html is like this:

```
<section class="todoapp">
      "<ccdacasd"
      <header class="header">
        <h1>todos</h1>
        <input class="new-todo" autofocus="autofocus" autocomplete="off" placeholder="What needs to be done?">
      </header>
    </section>
```

it will be wrong

**Comment by KingPixil** [comment]
Hey.

If you are using the HTML inside of an element to use as a template, it will be normalized by the browser before being sent over to Moon. You can also use the `template` option to set the template of the instance, and Moon will compile that template.

By the way, you will need to escape `<` and `>` to `&lt;` and `&gt;`

**Comment by wangning0** [comment]
Thanks for your reply~  I'll see it cafully carefully。
