### ISSUE TITLE
Booleans passed as props become strings

### ISSUE THREAD

**Issue by freezethrower** [KingPixil/moon#20]
Boolean value passed via props to component and then used as value for `m-if` directive appears as string, so `m-if` never receive `false`.
Here's [the pen that reproduces issue](http://codepen.io/freezethrower/pen/yMwaWr/).

**Comment by KingPixil** [comment]
Hey @freezethrower 

This is why there is a [`m-literal`](http://moonjs.ga/api/directives#-literal-) directive, to pass down props as a literal javascript expression.

**Comment by freezethrower** [comment]
Thanks, `m-literal` works as expected. It was not obvious from documentation that it works not only for standart HTML attributes like `id` or `class`, but for component props too.

**Comment by KingPixil** [comment]
Hmm, I'll try to make it more clear 👍
