### ISSUE TITLE
Documentation needs search

### ISSUE THREAD

**Issue by luminarious** [KingPixil/moon#21]
I'm very intrigued by Moon, given the size/functionality ratio. Unfortunately, the documentation right now is in serious need of some search, either Algolia or even Lunr.

I read in the docs that Moon supports computed properties as well, but to find how to use it, I resorted to Github search and found the example in tests.

**Comment by KingPixil** [comment]
Hey @luminarious 

Totally agree, the docs aren't even complete! There is still a lot of the API to get covered. I have yet to do the computed properties (as you said), a couple more directives in-depth, and more details on components.

Right now, the best place to find information is in the API docs, it has most of the instance and global methods, along with all of the directives. I'm planning to add a search also, and I'll keep everyone posted on the status of the site.

**Comment by awitherow** [comment]
@KingPixil is http://moonjs.ga/ open source so that people could contribute to the docs there?

**Comment by bovisp** [comment]
I second @awitherow 's request!

**Comment by KingPixil** [comment]
Of course! The docs are in the [gh-pages](https://github.com/KingPixil/moon/tree/gh-pages) branch.

**Comment by KingPixil** [comment]
Finally added search, sorry it took so long. It came along with v0.10.0
