### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by dpkpnm** [KingPixil/moon#26]
Looking into your library and I like what I am seeing ... keep up the good work

There is no info in the docs on how to implement a component.. 

I tried implementing it but it takes in data as string and prints list with "," any reason why this happens?

```
<script src="https://unpkg.com/moonjs"></script>
<div id="app1">
		<list data={{listdata}}></list>
	</div>
<script>
var list = Moon.component("list", {
		props:['data'],
		template:"<ul><li m-for='item in {{data}}'>{{item}}</li></ul>"
	})
	var app = new Moon({
		el:"#app1",
		data: {
			listdata:[0,1,2,3,4,5,6,7,8,9]	
		}
		
	})
</script>
```

**Comment by KingPixil** [comment]
Hey, this is a super common question.

Use `m-literal:data="{{listdata}}"`, to have the prop passed down as a literal javascript expression.

**Comment by dpkpnm** [comment]
thanks that worked

**Comment by dpkpnm** [comment]
How do you call methods from a component?

Can you do a tutorial on components when you have time... basic list component with all possible scenarios that would help alot... currently there is no way we can guess or know how this works.

**Comment by dpkpnm** [comment]
I was able to figure it out... adding methods in components it works.

My bad I was trying to access methods from the app ... instead of the component.
