### ISSUE TITLE
Multiple Adjacent instances of the same Component

### ISSUE THREAD

**Issue by alexmarchenko** [KingPixil/moon#27]
Placing same components side-by-side without wrapping at least one of them into plain HTML tag will result in TypeError: Cannot read property 'replaceChild' of null.

https://jsbin.com/qajelaw/edit?html,console,output

Is this an expected behavior and components should be wrapped into tags?

**Comment by KingPixil** [comment]
Fixed in 850ea1b4f75d2593017acbeba4649c1aaec5d085 (I think), and will be coming in v0.9.0
