### ISSUE TITLE
Can not seem to get computed properties to work

### ISSUE THREAD

**Issue by bovisp** [KingPixil/moon#28]
### Overview of the problem

This is about the Moon **JS framework**
I'm using Moon **0.8.0**
My **browser** is: Chrome 57.0.2987.133 (64-bit)
I am sure this issue is **not (well sort of not) a duplicate**

### Description

I am trying to use computed properties, which I saw had been added in early March 2017 (Issue #13). Since computed properties haven't been added to the docs, I decided to give it a kick at the can anyway, based on what I know about Vue. Sadly, I can't get it to work :-( .

**My issue may also extend to method calls as well.** 

### Steps to Reproduce

1. Consider this rather silly, yet simple, example:

```
var app = new Moon({
  el: "#app",
  
  data: {
    message: 'Hello World!'
  },

  computed: {
    reversedMessage () {
      return this.get('message').split('').reverse().join('')
    }
  }
})
```

2. ...and this HTML

```
<div id="app">
  <h4 m-text="reversedMessage"></h4>
</div>
```

### Expected behavior

The `reversedMessage` computed property method should fire, producing the following HTML:

```
<div id="app">
  <h4>!dlroW olleH</h4>
</div>
```

### Actual behavior

The way things are now, `reversedMessage` did not fire. Instead, it just rendered:

```
<div id="app">
  <h4>reversedMessage</h4>
</div>
```

**Comment by KingPixil** [comment]
Hey! You must pass an object with the getters/setters like:

```js
computed: {
    reversedMessage: {
      get() {
         return this.get('message').split('').reverse().join('')
      }
    }
}
```

**Comment by bovisp** [comment]
Gotcha! For completeness, here is the correct code:

JS:
```
var app = new Moon({
  el: "#app",

  data: {
    message: 'Hello World!'
  },

  computed: {
    reversedMessage: {
      get () {
        return this.get('message').split('').reverse().join('') 
      }
    }
  }
});
```

HTML:
```
<div id="app">
  <h4 m-text="{{reversedMessage}}"></h4>
</div>
```

**Comment by KingPixil** [comment]
By the way, the `m-text` directive will be removed in v0.9.0
