### ISSUE TITLE
Accessing data attributes?

### ISSUE THREAD

**Issue by kokujin** [KingPixil/moon#30]
Nice framework. How should one access data attributes for use in methods?
An example tag.

`````
<article
  id="electriccars"
  data-columns="3"
  data-index-number="12314"
  data-parent="cars">
</article>
`````

**Comment by pateketrueke** [comment]
I think `event.target.dataset` could work?

```
<button data-foo="bar" m-on:click="showData">Show me</button>
<script>
export default {
  methods: {
    showData(e) {
      console.log(e.target.dataset.foo); // bar
    },
  },
};
</script>
```

**Comment by KingPixil** [comment]
As @pateketrueke said, you can access it with `event.target.dataset`

The event object is passed to a method by default, and if you are passing custom parameters, you can use the special `event` keyword, like this:

```html
m-on:click="showData"
m-on:click="showData(event)"
m-on:click="showData('foo', event)"
```

**Comment by shellvip** [comment]
[(https://github.com/KingPixil/moon/blob/master/src/directives/default.js#L67)]
should pass the event parameter to callMethod?
const code = `function(event) {${modifiers}instance.callMethod("${methodToCall}", [${params}, event])}`;

**Comment by KingPixil** [comment]
I'm confused by what you're asking @shellvip 

By default, `event` is passed to a method. If you provide custom arguments, then those are provided instead.

**Comment by shellvip** [comment]
OK! I got it!
