### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by adekoyejoakinhanmi** [KingPixil/moon#32]
I tried to use pipe filters and there was an error. Are there any pipe filters functionalities? Thanks

**Comment by KingPixil** [comment]
Filters don't exist in Moon, you can just use a computed property (#13) in most cases, and adding a compiler for filters will also add a significant amount of weight.

I'm closing this for now (as you can use computed properties).

**Comment by adekoyejoakinhanmi** [comment]
I am still having issues using computed in the context that I mean too. Here are some code examples

`html
<div id="app">
  <header>{{title}}</header>
  <ul>
    <li m-for="item in {{DinoList}}">
      <h5>{{item.name}}</h5>
      <span> The <span {{item.name | capitalize}}</span> weighs {{item.weight}}.</span>
      <br>
      <a href="">https://en.wikipedia.org/wiki/{{item.name}}</a>
    </li>
  </ul>
</div>
`
and the js 
`JS
var app = new Moon({
  el : "#app",
  data : {
    title : "Dinosaurs",
    DinoList : [
      {name : "Velociraptor", weight : "15kg"}, 
      {name : "triceratops", weight : "2500kg"}, 
      {name : "stegosaurus", weight : "25kg"}]
  },
  computed : {
    capitalize : {
      get : function(val) {
        if (!val) return "";
        val = val.toString();
        return val.charAt(0).toUpperCase() + val.slice(1);
      }
    }
  }
});
`
How do I get the list items to pass the filter?

**Comment by adekoyejoakinhanmi** [comment]
I am still having problems getting the computed properties to work in context I mean to use them. Here:

```html
<div id="app">
  <header>{{title}}</header>
  <ul>
    <li m-for="item in {{DinoList}}">
      <h5>{{item.name}}</h5>
      <span> The <span {{item.name}}</span> weighs {{item.weight}}.</span>
      <br>
      <a href="">https://en.wikipedia.org/wiki/{{item.name}}</a>
    </li>
  </ul>
</div>
```

and here is the JS

```javascript
var app = new Moon({
  el : "#app",
  data : {
    title : "Dinosaurs",
    DinoList : [
      {name : "Velociraptor", weight : "15kg"}, 
      {name : "triceratops", weight : "2500kg"}, 
      {name : "stegosaurus", weight : "25kg"}]
  },
  computed : {
    capitalize : {
      get : function(val) {
        if (!val) return "";
        val = val.toString();
        return val.charAt(0).toUpperCase() + val.slice(1);
      }
    }
  }
});
```

How do I get the list items to pass through the capitalize property?

**Comment by KingPixil** [comment]
Computed properties are to be used as a single property that update when other properties are changed.

You can use a computed property to capitalize all of the elements in `DinoList`. Later, you can use a method, but I'm working on it, and it will likely be added in v0.10.0
