### ISSUE TITLE
Calling functions inside delimiters

### ISSUE THREAD

**Issue by adekoyejoakinhanmi** [KingPixil/moon#33]
Is it there a way to call functions inside of the delimited expressions for example:

```javascript
...
  computed : {
         add : {
             get : function (a, b) {
                  return a + b;
             }
         }
...
```

and in the html

```html
<p>{{add(1, 3)}}</p>
```

**Comment by KingPixil** [comment]
You can, but that is not what a computed property is for. You can use a method like this:

```html
<p>{{add(1, 3)}}</p>
<button m-on:click="add(1, 3)"></button>
```

```js
methods:  {
  add: function(a, b) {
    return a + b;
  }
}
```

Computed properties are used for  values that depend on others.

**Comment by adekoyejoakinhanmi** [comment]
Oh ok...I super excited for v0.9.0. Can't wait to try out the new features. I am currently building the tweetbox from "[A Vue.js introduction for people who know just enough jQuery to get by](https://medium.freecodecamp.com/vue-js-introduction-for-people-who-know-just-enough-jquery-to-get-by-eab5aa193d77)" but I am using MoonJS. Would share as soon as I am done.

**Comment by KingPixil** [comment]
Awesome! Can't wait to see it 👍 

I'm in the process of releasing v0.9.0 right now, just fixing up the docs.

**Comment by adekoyejoakinhanmi** [comment]
KingPixil -- Already using v.0.9.0 and it's really awesome. Well done. Here is the [link](https://codepen.io/cssJumper1995/full/LyVYzo/) to Moon Tweet box.
