### ISSUE TITLE
feature-request: support for dom-elements as `el` option

### ISSUE THREAD

**Issue by pateketrueke** [KingPixil/moon#34]
Currently, I cannot pass DOM instances as the `el` option, which is expecting an identifier.

https://github.com/KingPixil/moon/blob/5133bf21c64eccd4c49ca9b450f7ad558c30c64a/src/instance/methods.js#L151

I think something like this could work:

```js
this.$el = typeof el === 'string' ? document.querySelector(el) : el;
```

**Comment by KingPixil** [comment]
Should be coming in v0.9.1
