### ISSUE TITLE
how to fetch from REST API

### ISSUE THREAD

**Issue by juanbrujo** [KingPixil/moon#37]
I'm trying to fetch data from external json and can't figure out how, I'm using a kind of fechData fro VueJS (as both looks similar) and returning nothing. Any clues?

**Comment by juanbrujo** [comment]
I'm now using [axios](https://github.com/mzabriskie/axios) but maybe there's an internal method like `$.http` that's not documented.

**Comment by KingPixil** [comment]
Moon has no `http` module or methods yet, use axios for now. I might make it a separate plugin later.
