### ISSUE TITLE
Event listeners don't update correctly

### ISSUE THREAD

**Issue by adekoyejoakinhanmi** [KingPixil/moon#38]
After removing an item from a list. An error occurs when I try to update other items on the list. For example:
```html
<ul>
    <li m-for="dino in {{dinos}}">
      <button m-on:click="log({{dino}})">Log</button>
      {{dino.name}}
      <button m-on:click="removeDino({{dino}})">Make Extinct</button>
    </li>
  </ul>
```
Here is the JS:

```javascript
       data : {
		dinos : [
			{name : "Velociraptor", quantity : 5},
			{name : "Triceratops", quantity : 15},
			{name : "Stegosaurus", quantity : 10}
		]
	},
	methods : {
		log : function (dino) {
			var dinos = this.get("dinos");
			console.log(dino, dinos.indexOf(dino));
		},
		removeDino : function (dino) {
			let dinos = this.get("dinos");
			dinos.splice(dinos.indexOf(dino), 1);
			console.log(dinos);
			this.set("dinos", dinos);
		}
	} 
```

When I click removeDino() on the Triceratops, the DOM is updated. However, after removing it, I can't access Stegosaurus from the Data anymore. The DOM will show Stegosaurus but when I click the log button, I get `Object {name: "Triceratops", quantity: 15} -1`. Please can you help me fix this? Thanks

**Comment by KingPixil** [comment]
This is odd. I've tracked down the issue though. Essentially, Moon only adds the event listeners once, and the handler is bound to the first `dino`. After that, Moon doesn't update them any more, so the event listeners are mismatched.

Will be fixed in v0.10.0
