### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by jbmonroe** [KingPixil/moon#40]
Uncaught TypeError: Cannot set property '__moon__' of null
    at t.mount (unpkg.com/moonjs@0.9.0:7)
    at t.init (unpkg.com/moonjs@0.9.0:7)
    at new t (unpkg.com/moonjs@0.9.0:7)
    at main (main.js:31)
    at index.html:22

```
const app1 = new Moon(
    {
        el : "#app1",
        data : {
           msg : "There is a Moon"
        }
    }
);
```

**Comment by KingPixil** [comment]
It seems like there is no element to mount on (`div#app1` doesn't exist). Create an element with the id of `app1` and try again.

Also, it seems like you are using the production version of Moon. Use the development version if you'd like helpful development warnings. Link to `https://unpkg.com/moonjs@0.9.0/dist/moon.js`

**Comment by jbmonroe** [comment]
Yeah, agreed--did it this morning on a different computer and apparently didn't leave that div out--but I recall checking that.  Maybe I typed "appl" instead of "app1" and the font didn't show that clearly.
