### ISSUE TITLE
Observation: for..in slower than Object.keys

### ISSUE THREAD

**Issue by jbmonroe** [KingPixil/moon#42]
See https://jsperf.com/object-keys-vs-for-in-with-closure/3.

If the for...in loops enumerate lots of properties, using Object.keys gives a huge performance boost in most cases (at the expense of some extra memory).  If you're walking 4 items, perhaps no need to bother.  Wouldn't be job #1 until Moon is long-term feature complete anyway.

**Comment by KingPixil** [comment]
This is because of the `hasOwnProperty` check happening in the for..in test. Without this, they are almost equal (for..in is a little slower), but I think that's a good enough trade for the reduced memory usage.

Let me know what you think.

**Comment by jbmonroe** [comment]
What is the actual memory impact?  My rule of thumb on JS is that, given that we already know performance is an issue, that temporary memory spikes aren't that big of a deal.  Since JS only ever gives us arrays of references  (which are either 32- or 64-bit) it's not that much overhead, and it won't hang around long before the GC gets to it.

Functional programming principles never seem to include worrying about intermediate storage overhead, so what the heck, right?

**Comment by KingPixil** [comment]
Yes, but for..in is already as fast as Object.keys, the jsperf test is not a good representation of this, as it has a check using `hasOwnProperty`. This check calls a function, increasing the time it takes for each iteration.

Without this check they are essentially the same, and Moon uses it without the check. I'm closing this for now as it doesn't effect performance benchmarks.
