### ISSUE TITLE
Dynamically mounting a component?

### ISSUE THREAD

**Issue by kokujin** [KingPixil/moon#46]
Is there some example code on how to dynamically mount a component to a certain element during run-time? For example, using a button?
Thanks

**Comment by KingPixil** [comment]
A component can only be mounted through it being an element. Mounting one through a button could be done like this:

```html
<div id="app">
  <example m-if="mounted"></example>
  <button m-on:click="toggle">Mount</button>
</div>
```

```js
Moon.component("example", {
  template: "<h1>I'm an example component</h1>"
});

new Moon({
  el: "#app",
  data: {
    mounted: false
  },
  methods: {
    toggle: function() {
      this.set('mounted', !this.get('mounted'));
    }
  }
});
```

Here is a [jsFiddle demo](https://jsfiddle.net/tsnfehtz/)

**Comment by kokujin** [comment]
That defeats part of the flexibility of having templates and components, how would I be able to handle an application the can have large forms and sub apps if they are only to be seen if the user actually needs them, it would be sub optimal to try to render every possible combination of components beforehand.

**Comment by KingPixil** [comment]
A component can manage it's own state, and there is no other way for Moon to know if a component needs to be mounted.

This is exactly how you would accomplish it in Vue or React, and is how components work. You can't expect Moon to know how your application works. It is your responsibility to have the data needed to know when to render components.

If you'd like a router, check out [moon-router](https://github.com/KingPixil/moon-router)
