### ISSUE TITLE
Curious about checkboxes and radiobuttons

### ISSUE THREAD

**Issue by lutostag** [KingPixil/moon#52]
I was curious if moon works with multiple checkboxes with the same name. It seems to bind it all together if I use the same model. Also I can't seem to get radiobuttons to work. I was expecting similar to
https://vuejs.org/v2/guide/forms.html#Checkbox -- the 'Multiple checkboxes, bound to the same Array' bit and https://vuejs.org/v2/guide/forms.html#Radio.

My stab at seeing if it would work. Am I just doing something silly? https://jsfiddle.net/fw8spum7/
I see that the checkboxes with different names work fine. Just hoping you might want to cater to this use-case.

Thanks for a great slim front-end, just what I was looking for!

**Comment by KingPixil** [comment]
Hey!

You can use `m-model` to bind multiple checkboxes to a specific index of an array, and unlike Vue, you'll have the value in a guaranteed index. Vue, on the other hand, doesn't guarantee the index of the value of the checkbox in the array, but instead automates it.

I'll add a custom item to the code generator in v0.10.1 regarding radio buttons.

Let me know what you think

**Comment by adekoyejoakinhanmi** [comment]
Hi KingPixil, Since this is about radio boxes I decided not to open a new issue. Radio boxes with the same `m-model` value do update data model. Check this out:

```javascript
new Moon({
el : "#app",
data : {
	names : ['joe', 'peter', 'john', 'maxwell', 'jones'],
        person : 'joe'
}
});
```
And the html:
```html
<div id="app">
<label m-for="personName in names" >
  <input type="radio" m-model="person" m-literal:value="personName" m-literal:id="personName" />        {{personName}}
</label>

<br/>

  {{person}}
</div>
```

The radiobox doesn't change the value of `{{person}}` as expected. Or is there something I am missing?
