### ISSUE TITLE
Dynamic rendering

### ISSUE THREAD

**Issue by kokujin** [KingPixil/moon#53]
Here are a few lines of code that describes what I am trying to achieve:

**test.html**

``````
<body>
    <div id="app">
        <p>{{msg}}</p>
        <my-component></my-component>
        <div id="dynamic"></div>
    </div>

    <button id="daBtn">Add</button>

    <script src="js/vendor/jquery-1.12.0.min.js"></script>
    <script src="node_modules/moonjs/dist/moon.min.js"></script> 
    <script src="js/main.js"></script>
</body>

``````

**main.js**

``````
Moon.component('my-component', {
    template: "<h1>Custom Component</h1>"
});

var app = new Moon({
    el: "#app",
    data: {
        msg: "Hello Moon!"
    }
});

$('#daBtn').on('click', function(e) {
    e.preventDefault();
    $('#dynamic').append('<my-component></my-component>');
});
``````
What would be the best way to notify the DOM to re-render and thus showing the newly injected component?

Thanks

**Comment by KingPixil** [comment]
Hey,

This is not possible with Moon (or even Vue for that matter). See, to understand why you need to understand how Moon works. 

When you initialize your Moon instance, Moon is compiling your HTML to a render function. This render function is what renders the virtual DOM every time something changes. It will then compare this to the DOM, and apply the required changes.

When you append a new item to the DOM, Moon has no way of knowing, and when it builds a second time (when data changes), it will simply remove that element which is not part of the virtual DOM.

Another way to achieve this would be to use `m-if`.

```html
<body>
    <div id="app">
        <p>{{msg}}</p>
        <my-component></my-component>
        <div id="dynamic">
            <my-component m-for="i in components"></my-component>
        </div>
        <button id="daBtn" m-on:click="addComponent">Add</button>
    </div>

    <script src="node_modules/moonjs/dist/moon.min.js"></script> 
    <script src="js/main.js"></script>
</body>
```


```js
Moon.component('my-component', {
    template: "<h1>Custom Component</h1>"
});

var app = new Moon({
    el: "#app",
    data: {
        msg: "Hello Moon!",
        components: []
    },
    methods: {
      addComponent: function() {
        var components =  this.get('components');
        components.push(undefined);
        this.set('components', components);
      }
    }
});
```

This removes the need for JQuery. In later versions, you can iterate through a range (from 1-n) via `m-for` and there is no need for an array.

**Comment by adekoyejoakinhanmi** [comment]
@kokujin You do not need jQuery to work with Moon
