### ISSUE TITLE
Use Moon.config.keyCodes set keyCode doesn't work in component

### ISSUE THREAD

**Issue by shellvip** [KingPixil/moon#55]
when I set:
```
Moon.config.keyCodes({
  esc: 27
});
```
but in a component, `m-on:keyup.esc ` is not work

**Comment by KingPixil** [comment]
Can you give a jsFiddle reproducing the issue?

**Comment by shellvip** [comment]
I move the main code of your TodoMvc example to a component, but the m-on:keyup.esc does not work.

**Comment by KingPixil** [comment]
It should be working as intended, and is working in tests. If you can provide a demo of the issue, it would be of great help.

**Comment by shellvip** [comment]
When work with the .moon file for example: 
`require("./components/todo.moon")(Moon);`
the .esc modifier of `m-on:keyup.esc` not working in todo.moon

**Comment by shellvip** [comment]
In source code:
```
    let modifiers = "";
    for(var i = 0; i < rawModifiers.length; i++) {
      modifiers += eventModifiersCode[rawModifiers[i]];
    }
    // Final event listener code
    const code = `function(event) {${modifiers}instance.callMethod("${methodToCall}", [${params}])}`;
```

eventModifiersCode[rawModifiers[i]]; **//Maybe undefined**

**Comment by KingPixil** [comment]
Got it thanks! This is an issue with the code generator not knowing you registered a custom key code.
