### ISSUE TITLE
How to get component instances?

### ISSUE THREAD

**Issue by shellvip** [KingPixil/moon#57]

**Comment by KingPixil** [comment]
To get a component instance, you must access it by a method, hook, or computed property by using `this`.

**Comment by shellvip** [comment]
I can set the main Moon instance's data by `app.set('someData', 1)` in the console, but how can I set the component's data in the console?

**Comment by KingPixil** [comment]
Well Moon has no way of knowing which component instance you are referencing. For each component in the DOM, a new instance is created.

You can do something like:

```js
window.component = undefined;

Moon.component("example", {
  template: "<div>Example</div>",
  hooks: {
    mounted: function() {
      component = this;
    }
  }
});
```

After the component is initialized, a reference will be available through the console (`component`). Keep in mind this will reference to *one* component instance, as each component in the DOM has a corresponding instance.

**Comment by shellvip** [comment]
Mybe assigning a reference ID to the child component is a good solution.
https://vuejs.org/v2/guide/components.html#Child-Component-Refs

```
<div id="app">
  <example ref="exp1"></example>
  <example ref="exp2"></example>
  <example ref="exp3"></example>
</div>
```
then reference component like `app.$refs.exp1`
