### ISSUE TITLE
Fix Todo MVC example: Check item is not empty before creating

### ISSUE THREAD

**Issue by CodeBrauer** [KingPixil/moon#58]
In the current TodoMVC example you can add empty items.

Check out this: https://github.com/tastejs/todomvc/blob/master/app-spec.md#new-todo

And maybe you can contribute to TodoMVC by submitting moon: https://github.com/tastejs/todomvc/blob/master/contributing.md

**Comment by KingPixil** [comment]
I'll add that, and submit a PR to TodoMVC
