### ISSUE TITLE
Custom Directives

### ISSUE THREAD

**Issue by nakome** [KingPixil/moon#59]
**Hi**, I have a question ,how to make custom directive is this  posible?

Something like this:

```
Moon.directive('blue',(el) => {
  el.style.color = 'blue';
});

<p m-blue>{{title}}</p>
```

**Comment by KingPixil** [comment]
Yes, that is possible, refer to [the docs](http://moonjs.ga/api/global-api.html#-directive-]

**Comment by KingPixil** [comment]
Ahh, thanks for reporting the error! It was an issue with the compiler not generating correct code. Next time, use the [developer version](http://moonjs.ga/docs/installation.html) of Moon for a helpful error message.

This will be fixed in v0.11.0.

**Comment by nakome** [comment]
OK, Awesome project bro :+1:

**Comment by KingPixil** [comment]
Thank you! :smile:
