### ISSUE TITLE
Radio box not updating properly

### ISSUE THREAD

**Issue by adekoyejoakinhanmi** [KingPixil/moon#60]
Hi @KingPixil, Radio boxes with the same `m-model` value do update data model. Check this out:

```javascript
new Moon({
el : "#app",
data : {
	names : ['joe', 'peter', 'john', 'maxwell', 'jones'],
        person : 'joe'
}
});
```
And the html:
```html
<div id="app">
<label m-for="personName in names" >
  <input type="radio" m-model="person" name="person" m-literal:value="personName" m-literal:id="personName" />        {{personName}}
</label>

<br/>

  {{person}}
</div>
```

The radiobox doesn't change the value of `{{person}}` as expected. Or is there something I am missing?

**Comment by KingPixil** [comment]
Hey,

First of all, `m-model` is passing by value, meaning that you need to use it to refer to an index of an array, not the value of the item in the array. So you would change the value to `m-model="names[index]"`, and the value of the `m-for` to `"personName,index in names"`.

I'll be fixing `m-model` to work with radio buttons better in v0.11.0, by keeping a reference to the compiled value of regular attributes and `m-literal`.

**Comment by adekoyejoakinhanmi** [comment]
Okay, if this is the case. How then will I reference it in the view? i.e. how will I set the value of `{{person}}`

**Comment by KingPixil** [comment]
You can pass `{{person}}` to a method using `m-on` and it should pass by reference, but passing it through `m-model` would require Moon to detect this and compile it as Javascript (adding a lot of weight).

**Comment by KingPixil** [comment]
Alright! Sorry for the late fix, but the example you gave is now working!
