### ISSUE TITLE
dynamic class attribute overwritten by scoped CSS

### ISSUE THREAD

**Issue by nkoehring** [KingPixil/moon#68]
If moon single file components use `<style scoped>` the scope is applied via a unique class name. Elements with dynamic class names (eg `<h1 m-literal:class="{active: isActive}">`) end up with only the scope class.

**Comment by KingPixil** [comment]
I'm out of the country right now, I'll get back to this in a few weeks, thanks for reporting!

**Comment by KingPixil** [comment]
Alright, this was fixed in `moon-component-compiler`, and added in v0.0.4 of it. Specifically in [`7e9fc1b2ecd4e7107b9a4401bc5bf92ea65431b8`](https://github.com/KingPixil/moon-component-compiler/commit/7e9fc1b2ecd4e7107b9a4401bc5bf92ea65431b8).
