### ISSUE TITLE
Parent function cannot be invoked by child component

### ISSUE THREAD

**Issue by maiah** [KingPixil/moon#71]
html
```html
<script src="https://unpkg.com/moonjs"></script>

<div id="app">
  <my-component content="{{parentMsg}}" check="{{talk}}"></my-component>
</div>
```

JavaScript
```js
Moon.component('my-component', {
  props: ['content', 'check'],
  template: "<div><p>Data from Parent: {{content}}</p><button m-on:click='say'>SAY</button></div>",
  methods: {
      say: function() {
        this.callMethod("check");
    }
  }
});

const app = new Moon({
  el: "#app",
  data: {
    parentMsg: "yo"
  },
  methods: {
  	talk: function() {
    	alert("from parent " + this.get("parentMsg"));
    }
  }
});
```
html
```html
<script src="https://unpkg.com/moonjs"></script>

<div id="app">
  <my-component content="{{parentMsg}}" check="{{talk}}"></my-component>
</div>
```

JavaScript
```js
Moon.component('my-component', {
  props: ['content', 'check'],
  template: "<div><p>Data from Parent: {{content}}</p><button m-on:click='say'>SAY</button></div>",
  methods: {
      say: function() {
        this.callMethod("check");
    }
  }
});

const app = new Moon({
  el: "#app",
  data: {
    parentMsg: "yo"
  },
  methods: {
  	talk: function() {
    	  alert("from parent " + this.get("parentMsg"));
        }
  }
});
```

This `alert()` dialog is not shown when the user clicks SAY button. Or maybe I'm doing it the wrong way? How can the child component call a function from its parent? I supposed to do it via passing the parent's function thru props. But it doesn't work.

**Comment by KingPixil** [comment]
You CAN pass a function through props, you're just not passing it correctly. You are doing `check="{{talk}}"`.  Moon, by default, passes this prop as a string. To literally pass a value, you use the `m-literal` directive: `m-literal:check="talk"`.

**Comment by maiah** [comment]
I see. It's just not clear on the sample how to do this. I hope it will be added to the getting started guide. Anyways thanks for your help here really appreciated it.

And i like your framework and its API, for me it seems more elegant than vuejs. Calling `.set()` function is a clear way of saying that the component will rerender as needed. Great work for this! I hope there will be official state manager like vuex coming soon.

**Comment by KingPixil** [comment]
Thanks for the feedback! I'll add documentation on `m-literal`, including when and how to use it.

I'm super glad you like Moon. I'm working on a state manager right now, it's just not out yet.

**Comment by maiah** [comment]
Oh nice! Glad to hear that Moon will have its official state manager. I will keep an eye on this.

**Comment by KingPixil** [comment]
Hey @maiah! I've released an extremely basic official state manager for Moon, called [Monx](https://github.com/KingPixil/monx).

**Comment by maiah** [comment]
Lovely! I'll check it out. I will also incorporate this to the gopherjs wrapper for **moon** that i'm working on ;)

**Comment by KingPixil** [comment]
Glad you're interested. Can't wait to check out the cool project you're working on!

**Comment by maiah** [comment]
It's still work  in progress  hack&slash stuff in [Gopherjs](https://github.com/gopherjs/gopherjs), I will still need to create a full blown small app on it like todo list or something to see if it works well.
