### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by yanmagale** [KingPixil/moon#73]
Hello everyone.

I wanted to help with this project, but I want to know more about how to contribute to this project. Do not see anything about it.

**Comment by KingPixil** [comment]
Hey! 

I'm super happy you want to help out. I can add a `CONTRIBUTING.md` with a guide on how people should contribute. Also, I can give you some tips on what to do if you'd like.

**Comment by KingPixil** [comment]
Fixed in f2dd973

**Comment by yanmagale** [comment]
Excelent @KingPixil , thanks. I will read it :smile: . Yes, some tips would be pretty cool.

**Comment by KingPixil** [comment]
Thanks @yanmagale! If you have any questions about the code, structure, or contributing in general, feel free to ask.
