### ISSUE TITLE
Template not updating with class as data attribute

### ISSUE THREAD

**Issue by rogierverbrugge** [KingPixil/moon#75]
I'm trying out Moon as I like the small footprint over Vue but my view won't update if I call errors.get('title').

My data has a errors: new Errors() and on a ajax call I set the errors on the class.

Any idea how my view can auto update the error messages?

**Comment by KingPixil** [comment]
I'm confused, is `Errors` a Moon component? If it is, then calling `get` shouldn't update the view, as it is simply getting a value from the data and returning it. To set new data (and update the view), you can use `set`.

Please give me some more information, and I'll be glad to help you out.

**Comment by rogierverbrugge** [comment]
No `Errors` is a simple Class with a `get()` and `record()` methods which holds all my errors from the AJAX response (if any). If an error is set for a specific input field I want to see the error-message. 

With vue i use `this.data.errors.record()` which works and the view gets updated. Tried `this.$data.errors.record()` and the data is set, but view didn't update.

I presume I can't use the `set()` method or should I create a new `Errors` instance and replace the exising one with `set()`?

**Comment by KingPixil** [comment]
Ahh, got it. This is because Moon doesn't know you are updating the data, as it is observing only the `errors` attribute. Moon will only know to update the view if using `.set`. It is also generally unsafe and a bad practice to use `this.$data` in Moon, as it can be changed by the observer.

To use `record`, you can use:

```js
this.get("errors").record();
```

To manually rebuild the view, you can use:

```js
this.build();
```

**Comment by rogierverbrugge** [comment]
Thanks man! Totally works!

**Comment by KingPixil** [comment]
No problem!
