### ISSUE TITLE
Using jQuery plugin with Moon.js

### ISSUE THREAD

**Issue by terrybr** [KingPixil/moon#76]
Hello,

First of all, thank you so much for Moon.js.  This is exactly what I needed.

My first project using Moon must use a jQuery plugin.  I was able to follow some instructions for Vue.js and adapt it to Moon. (http://vuejsdevelopers.com/2017/05/20/vue-js-safely-jquery-plugin/)

Everything works perfectly except that I can't pass data from jQuery back to Moon.  If you check the link above,  there's a section called "Passing data from jQuery to Vue".  I tried updating a value inside Moon's data object, but it didn't work.  Here's my component:

```js
Moon.component("ztree", {
    props: ['id'],
    template: '<ul id="{{id}}" class="ztree"></ul>',
    hooks : {
        mounted: function() {
            var self = this;
            var settings = {
                callback: {
                    onClick: function(event, treeId, treeNode, clickFlag) {
                        self.emit('msg', treeNode.name);
                    }
                }
            }
            var tree = $.fn.zTree.init($(this.$el), settings, zNodes);
        }
    }
}); 
```

The issue here is inside the onClick callback.  "self.emit('msg', treeNode.name);" returns this error:

**TypeError: can't assign to properties of (new String("Node Name")): not an object**

I also tried with "self.set('msg', treeNode.name);" but nothing gets updated.

Is it a bug or what am I doing wrong?

Thank you for any help you can provide.

Terry

**Comment by KingPixil** [comment]
`emit` is used to fire an event, and the second parameter is supposed to be a context object which is passed to any event listeners.

You can do something like:

```js
self.emit('msg', {name: treeNode.name});
```

**Comment by terrybr** [comment]
It's not working since 'msg' isn't an event.  What I want to do is to update the 'msg' value which is in the data object of my Moon instance.   Here's my Moon instance:

`
    const app = new Moon({
        el: "#app1",
        data: {
            msg: "Node name will be here...",
            tree_id: 'treeDemo'
        }
    });
`

 How can I do that from inside a component?

**Comment by KingPixil** [comment]
Ahh, then you should be using `set`, which is used to update a value.

```
self.set('msg', treeNode.name);
```

**Comment by terrybr** [comment]
That's what I do, but the DOM is not refreshing with the new value.

**Comment by KingPixil** [comment]
Can you give me a jsFiddle reproducing the issue? It will make it much easier for me to help you out.

**Comment by terrybr** [comment]
I think it'd be easier for me to attach a zip file with the project.  Hopefully it's OK for me to do that.
Here it is:

[moon_test.zip](https://github.com/KingPixil/moon/files/1123349/moon_test.zip)

**Comment by KingPixil** [comment]
Thank you! I got the issue, `self` is referring to the component data, but the `msg` is defined on the parent Moon instance data.

To overcome this, you can listen for an event on a global event bus, and set the `msg` property *on the parent instance* when the event is fired.

```js
var bus = new Moon();
var t = $("#ztree_tmpl").text();

// ztree moon component
Moon.component("ztree", {
  props: ["id"],
  template: '<ul id="{{id}}" class="ztree"></ul>',
  hooks: {
    mounted: function() {
      var self = this;
      var settings = {
        callback: {
          onClick: function(event, treeId, treeNode, clickFlag) {
            bus.emit("msgChange", {
              msg: treeNode.name
            });
          }
        }
      };

      var tree = $.fn.zTree.init($(this.$el), settings, zNodes);
    }
  }
});

const app = new Moon({
  el: "#app1",
  data: {
    msg: "Node name will be here...",
    tree_id: "treeDemo"
  }
});

bus.on('msgChange', function(ctx) {
  app.set("msg", ctx.msg);
});
```
