### ISSUE TITLE
Search by initials at the same time

### ISSUE THREAD

**Issue by emresaracoglu** [KingPixil/moon#81]
We can search for content, that's good! Can we search with the **initials** of the content?

_For example:_

"`Oh you're perfectly welcome, sir.`" => "`oypws`"

How can a search made in this way be done?

http://moonjs.ga/examples/search/index.html

**Comment by KingPixil** [comment]
I don't think this is the right place to make an issue on the search, as it is merely a basic example on how to use Moon with [Wade](https://github.com/KingPixil/wade). 

Plus, searching by initials is going to get a little complex...how would I detect that the user is searching for initials? Most search platforms out there (including Google, Algolia, etc) don't have a similar feature. If you'd like, you can just write a custom function for that, but I don't think I will be adding it anytime soon.
