### ISSUE TITLE
HTTP Module

### ISSUE THREAD

**Issue by wilsontov** [KingPixil/moon#82]
Moon have a HTTP Module?
I mean, i want consume a simple API but i dont know if i can do it with Moon

**Comment by KingPixil** [comment]
Moon doesn't have an HTTP module (as of now), but you can easily integrate [axios](https://npm.im/axios) with Moon, just communicate with your API in a method and then update the data then.

**Comment by wilsontov** [comment]
Thank you! :smile:

**Comment by KingPixil** [comment]
No problem!
