### ISSUE TITLE
js-framework-benchmark

### ISSUE THREAD

**Issue by leeoniya** [KingPixil/moon#84]
hey @KingPixil,

would you be interested in submitting a pull request for Moon (keyed and non-keyed impls): https://github.com/krausest/js-framework-benchmark

would be interesting to see the results, thanks!

**Comment by KingPixil** [comment]
Sure! I'll start working on an implementation.

**Comment by leeoniya** [comment]
sweet :) it certainly helped me iron out some slowness in https://github.com/leeoniya/domvm

if you have any questions about getting it running, lemme know.

**Comment by KingPixil** [comment]
For sure! Keep up the great work on domvm! 👍

**Comment by KingPixil** [comment]
Alright, I submitted a [PR](https://github.com/krausest/js-framework-benchmark/pull/212).
