### ISSUE TITLE
How to empty data?

### ISSUE THREAD

**Issue by giordanovi** [KingPixil/moon#88]
How to empty data object without delete methods? Thank you

**Comment by KingPixil** [comment]
You can't delete a property without the `delete` keyword, but if you just want to set everything to undefined, you can do:

```js
for(let key in this.$data) {
  this.$data[key] = undefined;
}

this.build();
```

**Comment by giordanovi** [comment]
This will set to `undefined` methods too.
There is a way to set to `undefined` just data?

**Comment by KingPixil** [comment]
Ahh, well you can do something like:

```js
```

**Comment by KingPixil** [comment]
Closing for now, let me know if you need more help with clearing data.
