### ISSUE TITLE
How to get original dom event?

### ISSUE THREAD

**Issue by liuhann** [KingPixil/moon#92]
The code below works right but I got  error thrown

`<input m-on:change="imageSelected(event)">`

moon.js:179 [Moon] ERROR: The item "event" was not defined but was referenced

**Comment by KingPixil** [comment]
This is actually a bug in the compiler. Thanks for reporting!

**Comment by Marc-oO** [comment]
Hello,

this bug seems to be fixed, but i still have this warning : 

> [Moon] ERROR: The item "event" was not defined but was referenced

( https://codepen.io/anon/pen/wPXKrR?editors=1111 )

Regards

**Comment by kbrsh** [comment]
@Marc-oO That's another bug ;)

It has also been fixed in the current v1 development.
